from math import 
print('{:=^40}'.format('TABUADA'))
numero = int(input('Digite um numero ! '))
print('1  X  {} = {}'.format(numero,numero*1))
print('2  X  {} = {}'.format(numero, numero*2))
print('3  X  {} = {}'.format(numero, numero*3))
print('4  X  {} = {}'.format(numero, numero*4))
print('5  X  {} = {}'.format(numero, numero*5))
print('6  X  {} = {}'.format(numero, numero*6))
print('7  X  {} = {}'.format(numero, numero*7))
print('8  X  {} = {}'.format(numero, numero*8))
print('9  X  {} = {}'.format(numero, numero*9))
print('10 X  {} = {}'.format(numero, numero*10))
for tabu in range(0, 11):
    print(tabu)