a = input('Digite algo ')
print('É uma letra ?',a.isalpha())
print('É um numero ?',a.isnumeric())
print('É alfanumerico ?',a.isalnum())
print('Só tem espaço ?',a.isspace())
print('Esta em maiusculo ?',a.isupper())
print('Esta em minusculo ?',a.islower())
print('Esta em maiusculo e minusculo ?',a.istitle())
