nome = input('Qual é o seu nome ? ')
print('Olá' ,nome,'Prazer em conhece-lo ')
hobbie = input('Me diga qual é o seu hoobie ? ' )
print('Realmente' , hobbie, 'é muito interessante ')
idade=input('Quantos anos você tem ? ')
