print('Qual é a capital do Brasil')
print('(A)Brasilia')
print('(B)Rio de Janeiro')
print('(C)São Paulo')
print('(D)Belo Horizonte')
r = input('Resposta ')
a = print('Acertou !!')
b = print('Errou')
c = print('Errou')
d = print('Errou')

